config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :vacations do
      resources :items
      resources :activities
    end
  end


  root 'welcome#index'
  #get 'users/auth/twitter/callback', to: 'sessions#create'

  #resources :users do
  #  resources :vacations
  #end
  #delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :vacations
  has_many :users, through: :vacations

  scope :completed, -> { where(completed: true) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :vacations
  has_many :users, through: :vacations
end

app/models/user.rb
class User < ApplicationRecord
  has_many :vacations
  has_many :activities, through: :vacations
  has_many :items, through: :vacations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:twitter]

  def self.find_for_oauth(auth)
     find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  belongs_to :item  
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.create(activity_params)
    redirect_to vacation_activity_path(@activity)
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :activity_category, :user_id, :vacation_id)
  end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.create(activity_params)
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :activity_category, :user_id, :vacation_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def index
      @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    redirect_to items_path
  end

  def edit
    @item = Item.find_by(params[:id])
  end

  def update
    @item = Item.find_by(params[:id])
    @item.update(item_params)
  end

  def destroy
    @item = Item.find_by(params[:id])
    @item.destroy
    redirect_to root_path, :notice => "Your item was deleted."
  end


  private

  def item_params
    params.require(:item).permit(:name, :item_category, :user_id, :vacation_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = "Sucessfully logged out!"
    end
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  def index
    if params[:user_id]
      @vacations = User.find(params[:user_id]).vacations
    else
      @vacations = Vacation.all
    end
  end

  def show
    @vacation = Vacation.find(params[:id])
  end

  def new
    @vacation = Vacation.new
    @user = User.find_by(params[:id])
  end

  def create
    @vacation = Vacation.create(vacation_params)
    redirect_to vacations_path
  end

  def edit
    @vacation = Vacation.find_by(params[:id])
  end

  def update
    @vacation = Vacation.find_by(params[:id])
    @vacation.update(vacation_params)
  end

  def destroy
    @vacation = Vacation.find_by(params[:id])
    @vacation.destroy
    redirect_to root_path, :notice => "Your vacation was deleted."
  end

  private

  def vacation_params
    params.require(:vacation).permit(:name, :destination, :start, :end, :user_id, :item_id, :activity_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vacation_helper.rb
module VacationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/new.html.erb
<%= form_for :activity do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />

  <%= f.label :activity_category %>
  <%= f.text_field :activity_category %><br />

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Family Vacation Planner</title>
    <link rel="stylesheet" href="https://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css">
    <link rel='stylesheet' href='style.css'/>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="menu">
      <div class="container">
        <ul class="nav">
          <a href="<%= root_path %>"><img src="https://i.imgur.com/AaSpC3c.png?1" title="source: imgur.com"/></a>
          <% if user_signed_in? %>
            <li>Logged in as
              <strong><%= current_user.email %></strong>
            </li>
            <li><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
            <% else %>
              <li><%= link_to "SIGN UP", new_user_registration_path, :class => 'navbar-link' %></li>
              |
              <li><%= link_to "SIGN IN", new_user_session_path, :class => 'navbar-link' %></li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="main">
        <div class="container">
          <div class="row">
            <div class="col-md-5">
              <div class="form">
                <% if notice %>
                  <p class="alert alert-success"><%= notice %></p>
                <% end %>
                <% if alert %>
                  <p class="alert alert-danger"><%= alert %></p>
                <% end %>

                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="footer">
  <div class="container">
    <ul>
      <li>
        <%= link_to 'Home', root_path %>
      </li>
      <li>
        <%= link_to 'My Vacations', vacations_path %>
      </li>
    </ul>
    <p>&copy;2018 Family Vacation Planner</p>
  </div>
</div>
</body>
</html>

app/views/vacations/_form.html.erb
<hr>
<%= form_for @vacation do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name%><br />

  <%= f.label :destination %><br />
  <%= f.text_field :destination%><br />

  <%= f.label :start %><br />
  <%= f.date_select :start , {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year + 5, end_year: Date.today.year}, {required: true} %><br />

  <%= f.label :end %><br />
  <%= f.date_select :end , {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year + 5, end_year: Date.today.year}, {required: true} %><br /><br>

  <%= f.label "Add Activity" %><br>
  <%= f.fields_for :activities do |act_fields| %>
    Name: <%= act_fields.text_field :name %><br>
    Category: <%= act_fields.text_field :activity_category %>
  <% end %>
  <br><br>
  <%= f.label "Add Item" %><br>
  <%= f.fields_for :items do |item_fields| %>
    Name: <%= item_fields.text_field :name %><br>
    Category: <%= item_fields.text_field :item_category %>
  <% end %><br><br>
  <%= f.submit %>
<% end %>

app/views/vacations/edit.html.erb
<h3><strong>Edit Vacation</strong></h3>
<%= render 'form' %><br>
<%= link_to "Go Back", root_path %>

app/views/vacations/index.html.erb
<div class="trips">
  <h4>My Vacations</h4>
    <hr>
      <%= @vacations.each do |v| %>
          <h4><%= link_to v.name, vacation_path(v) %></h4>
          <%= link_to "Edit Vacation", edit_vacation_path(v) %> |
          <%= link_to "Add Activity", new_vacation_activity_path(v) %> |
          <%= link_to "Cancel Vacation", vacation_path(v), :confirm => "Are you sure?", :method => :delete %>
      <% end %>
    </div>
      <%= button_to "Create New Vacation", new_vacation_path(@user) %>

app/views/vacations/new.html.erb
<%= form_for @vacation do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name%><br />

  <%= f.label :destination %><br />
  <%= f.text_field :destination%><br />

  <%= f.label :travelers %><br />
  <%= f.text_field :traveler %><br />

  <%= f.label :start %><br />
  <%= f.date_select :start , {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year + 5, end_year: Date.today.year}, {required: true} %><br />

  <%= f.label :end %><br />
  <%= f.date_select :end , {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year + 5, end_year: Date.today.year}, {required: true} %><br /><br>

  <%= f.submit "Create New Vacation" %>
<% end %>

app/views/vacations/show.html.erb
<ul>
  <li>Name: <%= @vacation.name %></li>
  <li>Destination: <%= @vacation.destination %></li>
  <li>Travelers: <%= @vacation.traveler %></li>
  <li>Start: <%= @vacation.start.strftime('%B %d, %Y') %></li>
  <li>End: <%= @vacation.end.strftime('%B %d, %Y') %></li>
  <li>Activities: <%= @vacation.activities.name %></li>
  <%= link_to "Edit Vacation", edit_vacation_path(@vacation) %> |
  <%= link_to "Cancel Vacation", vacation_path(@vacation), :confirm => "Are you sure?", :method => :delete %>
</ul>

app/views/welcome/index.html.erb
<h4>Welcome back <%= current_user.email %></h4>
<hr>